export const musicControl = document.querySelector(".music-grid")
export const forest = document.getElementById("forest")
export const rain = document.getElementById("rain")
export const shop = document.getElementById("shop")
export const fire = document.getElementById("fire")